import { library, config } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faBars,
  faGlobe,
  faPhone,
  faSpinner,
  faTimes,
  faCloudUpload,
  faFileChartLine,
  faCloud,
  faFileUpload,
  faBolt,
  faShieldAlt,
  faEnvelope,
  faStar,
} from '@fortawesome/pro-light-svg-icons'
import {
  faFacebook,
  faFacebookF,
  faInstagram,
  faLinkedin,
  faTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'
import {
  customIcon,
  redIcon,
  greenIcon,
  orangeIcon,
} from 'assets/js/custom-icons'
import { faCircle, faCircleXmark } from '@fortawesome/free-solid-svg-icons'

library.add(
  faBars,
  faTimes,
  faFacebook,
  faFacebookF,
  faInstagram,
  faLinkedin,
  faTwitter,
  faYoutube,
  customIcon,
  redIcon,
  greenIcon,
  orangeIcon,
  faAngleLeft,
  faAngleRight,
  faAngleDown,
  faAngleUp,
  faPhone,
  faGlobe,
  faSpinner,
  faCircle,
  faCloudUpload,
  faFileChartLine,
  faCloud,
  faFileUpload,
  faBolt,
  faShieldAlt,
  faEnvelope,
  faCircleXmark,
  faStar
)
